#!/usr/bin/env python3
"""
H2O AutoML Retraining - Online / Incremental

Purpose:
    Load merged retraining Parquet data from GCS, retrain the H2O AutoML
    model on the expanded dataset, log metrics to MLflow, and register
    a new version of the model in the MLflow Registry.

    This script is called by Airflow DAG `model_retrain_hourly` every hour.

Input:
    gs://big-data-group-4-gold/features/retrain/YYYYMMDD_HH/
    (generated by spark_merge_data task)

Output:
    MLflow experiment run with metrics, new model version in Registry.
    Flink automatically picks up the latest version.

Differences from h2o_before_2020.py:
    - Reads from dynamic GCS path (latest merged data).
    - Tags the run as "retrain_online".
    - Uses the same H2O AutoML + MLflow logging logic.
"""

import logging
import os
import re
import json
import tempfile
import time
from pathlib import Path
from typing import Sequence

import h2o
from h2o.automl import H2OAutoML
from h2o.estimators.gbm import H2OGradientBoostingEstimator
from h2o.estimators.glm import H2OGeneralizedLinearEstimator
from h2o.estimators.naive_bayes import H2ONaiveBayesEstimator
import mlflow
import mlflow.h2o
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_recall_fscore_support,
)

# ============================================================
# Logging
# ============================================================

logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger("h2o-retrain-online")


# ============================================================
# Configuration
# ============================================================

# Dynamic path - use the latest merged retrain data from local Gold or GCS Gold.
DEFAULT_DATA_PATH = os.getenv(
    "RETRAIN_DATA_PATH",
    os.getenv(
        "GOLD_RETRAIN_CSV_PATH",
        os.getenv("GOLD_RETRAIN_PATH", "gs://big-data-group-4-gold/features/retrain/"),
    ),
)

MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI", "http://10.128.0.4:5000")
MLFLOW_EXPERIMENT_NAME = os.getenv("MLFLOW_EXPERIMENT_NAME", "traffic-risk-assessment")

MODEL_NAME = os.getenv("ML_MODEL_NAME", "traffic-risk-model")
MAX_RUNTIME_SECS = int(
    os.getenv("H2O_MAX_RUNTIME", "600")
)  # Shorter for hourly retrain
H2O_MAX_MEM = os.getenv("H2O_MAX_MEM", "2G")
H2O_NTHREADS = int(os.getenv("H2O_NTHREADS", "2"))
H2O_IP = os.getenv("H2O_IP", "127.0.0.1")
H2O_PORT = int(os.getenv("H2O_PORT", "54321"))
TOP_K_MODELS = max(1, int(os.getenv("H2O_TOP_K_MODELS", "10")))
H2O_MAX_MODELS = max(TOP_K_MODELS, int(os.getenv("H2O_MAX_MODELS", str(TOP_K_MODELS))))
H2O_ENFORCE_FULL_TOP_K = (
    os.getenv("H2O_ENFORCE_FULL_TOP_K", "true").lower() == "true"
)
H2O_NFOLDS = int(os.getenv("H2O_NFOLDS", "0"))
H2O_EXCLUDE_ALGOS_RAW = os.getenv(
    "H2O_EXCLUDE_ALGOS",
    "DeepLearning,StackedEnsemble,XGBoost",
).strip()
H2O_EXCLUDE_ALGOS = [
    item.strip() for item in H2O_EXCLUDE_ALGOS_RAW.split(",") if item.strip()
]
H2O_TRAIN_MAX_ROWS = int(os.getenv("H2O_TRAIN_MAX_ROWS", "2000000"))
H2O_EVAL_MAX_ROWS = int(os.getenv("H2O_EVAL_MAX_ROWS", "25000"))
H2O_MAX_AFTER_BALANCE_SIZE = float(os.getenv("H2O_MAX_AFTER_BALANCE_SIZE", "1.0"))
H2O_MAX_RUNTIME_SECS_PER_MODEL = int(os.getenv("H2O_MAX_RUNTIME_SECS_PER_MODEL", "120"))
H2O_BALANCE_CLASSES = os.getenv("H2O_BALANCE_CLASSES", "false").lower() == "true"
H2O_FALLBACK_PER_MODEL_RUNTIME_SECS = int(
    os.getenv(
        "H2O_FALLBACK_PER_MODEL_RUNTIME_SECS",
        str(max(20, min(H2O_MAX_RUNTIME_SECS_PER_MODEL, 60))),
    )
)
RETRAIN_BATCH_ID = os.getenv("RETRAIN_BATCH_ID", os.getenv("SPARK_BATCH_ID", "")).strip()
NODE3_STATUS_FILE = os.getenv("NODE3_STATUS_FILE", "").strip()
USE_CLASS_SAMPLING_FACTORS = (
    os.getenv("H2O_USE_CLASS_SAMPLING_FACTORS", "true").lower() == "true"
)
MAX_CLASS_SAMPLING_FACTOR = float(os.getenv("H2O_MAX_CLASS_SAMPLING_FACTOR", "100.0"))

# Label column in the Parquet/CSV
LABEL_COLUMN = "true_severity"

# Columns to exclude from feature vector
EXCLUDED_COLUMNS = {
    "event_id",
    "event_year",
    "event_time",
    "true_severity",
    "ingestion_time_epoch",
    "processed_time_epoch",
    "end_to_end_latency_ms",
}

SEED = int(os.getenv("H2O_SEED", "42"))
VALID_INCREMENTAL_BATCH_PATTERN = re.compile(r"^\d{8}T\d+Z$")


# ============================================================
# Helper: Safely log metrics that may not be available
# ============================================================
def log_metric_if_exists(perf, metric_name, mlflow_name=None, log_prefix="  "):
    """Safely extract a metric from H2O performance and log to MLflow + console."""
    if mlflow_name is None:
        mlflow_name = metric_name

    try:
        if metric_name in ("F1", "precision", "recall", "specificity", "sensitivity"):
            if hasattr(perf, metric_name):
                values = getattr(perf, metric_name)()
                for row in values:
                    class_label = row[0]
                    val = float(row[1])
                    mlflow.log_metric(f"{mlflow_name}_class_{class_label}", val)
                    logger.info(
                        "%s%s (class %s):          %.6f",
                        log_prefix,
                        metric_name.capitalize(),
                        class_label,
                        val,
                    )
                return True
        elif hasattr(perf, metric_name):
            val = float(getattr(perf, metric_name)())
            if not (val != val):  # NaN check
                mlflow.log_metric(mlflow_name, val)
                logger.info(
                    "%s%s:                   %.6f",
                    log_prefix,
                    metric_name.capitalize(),
                    val,
                )
                return True
    except (KeyError, AttributeError, TypeError, ValueError):
        pass

    logger.info("%s%s:                   N/A", log_prefix, metric_name.capitalize())
    return False


def shutdown_existing_local_h2o():
    """Stop a stale local H2O cluster so each retrain starts from a clean JVM."""
    cluster_url = f"http://{H2O_IP}:{H2O_PORT}"
    logger.info("Checking for an existing local H2O cluster at %s...", cluster_url)

    try:
        h2o.connect(url=cluster_url, verbose=False)
    except Exception:
        logger.info("No existing local H2O cluster detected.")
        return

    try:
        logger.warning(
            "Found an existing local H2O cluster at %s. Shutting it down before retraining.",
            cluster_url,
        )
        h2o.cluster().shutdown(prompt=False)
        time.sleep(5)
    except Exception as exc:
        logger.warning("Could not cleanly shut down the existing H2O cluster: %s", exc)
    finally:
        try:
            h2o.connection().close()
        except Exception:
            pass


def evaluate_classifier_with_sklearn(
    model,
    test_frame,
    feature_columns: list[str],
    label_column: str,
) -> tuple[dict[str, float], pd.DataFrame, pd.DataFrame]:
    """
    Compute complete multiclass classification metrics for retraining runs.

    The online retraining report must remain comparable to the offline
    pretraining report, so this helper logs the same accuracy, macro F1,
    weighted F1, precision, recall, per-class metrics, and confusion matrix.
    """
    prediction_frame = model.predict(test_frame[feature_columns])
    prediction_df = prediction_frame.as_data_frame()
    y_pred = prediction_df["predict"].astype(str)
    y_true = test_frame[label_column].as_data_frame()[label_column].astype(str)
    labels = sorted(
        set(y_true.tolist()) | set(y_pred.tolist()), key=lambda value: int(float(value))
    )

    precision, recall, f1, support = precision_recall_fscore_support(
        y_true,
        y_pred,
        labels=labels,
        zero_division=0,
    )

    macro = precision_recall_fscore_support(
        y_true, y_pred, labels=labels, average="macro", zero_division=0
    )
    weighted = precision_recall_fscore_support(
        y_true, y_pred, labels=labels, average="weighted", zero_division=0
    )

    metrics = {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "macro_precision": float(macro[0]),
        "macro_recall": float(macro[1]),
        "macro_f1": float(
            f1_score(y_true, y_pred, labels=labels, average="macro", zero_division=0)
        ),
        "weighted_precision": float(weighted[0]),
        "weighted_recall": float(weighted[1]),
        "weighted_f1": float(
            f1_score(y_true, y_pred, labels=labels, average="weighted", zero_division=0)
        ),
    }

    report_df = pd.DataFrame(
        {
            "class_label": labels,
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "support": support,
        }
    )
    matrix = confusion_matrix(y_true, y_pred, labels=labels)
    confusion_df = pd.DataFrame(
        matrix,
        index=[f"actual_{label}" for label in labels],
        columns=[f"predicted_{label}" for label in labels],
    )
    return metrics, report_df, confusion_df


def log_classifier_metrics(
    metrics: dict[str, float],
    report_df: pd.DataFrame,
    confusion_df: pd.DataFrame,
    artifact_prefix: str,
) -> None:
    """Log sklearn metrics and CSV artifacts to MLflow and training logs."""
    for metric_name, metric_value in metrics.items():
        mlflow.log_metric(metric_name, metric_value)
        logger.info("  %-24s %.6f", metric_name + ":", metric_value)

    for _, row in report_df.iterrows():
        class_label = str(row["class_label"])
        mlflow.log_metric(f"class_{class_label}_precision", float(row["precision"]))
        mlflow.log_metric(f"class_{class_label}_recall", float(row["recall"]))
        mlflow.log_metric(f"class_{class_label}_f1", float(row["f1"]))
        mlflow.log_metric(f"class_{class_label}_support", float(row["support"]))

    logger.info("  Per-class classification report:\n%s", report_df)
    logger.info("  Confusion matrix table:\n%s", confusion_df)

    with tempfile.TemporaryDirectory() as tmpdir:
        report_path = os.path.join(
            tmpdir, f"{artifact_prefix}_classification_report.csv"
        )
        confusion_path = os.path.join(tmpdir, f"{artifact_prefix}_confusion_matrix.csv")
        report_df.to_csv(report_path, index=False)
        confusion_df.to_csv(confusion_path)
        mlflow.log_artifact(report_path, artifact_path="metrics")
        mlflow.log_artifact(confusion_path, artifact_path="metrics")


def build_class_sampling_factors(label_distribution) -> tuple[list[float] | None, dict]:
    """
    Compute bounded H2O class sampling factors from the observed label distribution.

    Online retraining data can be more imbalanced than the offline split. This
    helper keeps the rare-class treatment explicit, reproducible, and bounded
    so hourly retraining remains stable on CPU-based VMs.
    """
    if not USE_CLASS_SAMPLING_FACTORS:
        return None, {}

    distribution_df = label_distribution.as_data_frame()
    label_column = distribution_df.columns[0]
    count_column = "Count"
    counts = {
        str(int(float(row[label_column]))): float(row[count_column])
        for _, row in distribution_df.iterrows()
    }
    if not counts:
        return None, {}

    max_count = max(counts.values())
    ordered_labels = sorted(counts.keys(), key=lambda value: int(float(value)))
    factors = [
        round(min(max_count / counts[label], MAX_CLASS_SAMPLING_FACTOR), 6)
        for label in ordered_labels
    ]
    metadata = {
        "ordered_labels": ordered_labels,
        "class_counts": counts,
        "class_sampling_factors": factors,
        "max_class_sampling_factor": MAX_CLASS_SAMPLING_FACTOR,
    }
    return factors, metadata


def sample_frame_rows(
    frame: h2o.H2OFrame,
    frac: float,
    seed: int,
    reason: str,
) -> h2o.H2OFrame:
    """
    Return a sampled subset without materializing an explicit complement frame.

    `split_frame()` creates both sides of the split, which was causing avoidable
    heap pressure on the small Node3 retraining VM. Here we only keep the rows
    we actually need.
    """
    bounded_frac = max(0.0001, min(1.0, float(frac)))
    if bounded_frac >= 1.0:
        return frame

    logger.info(
        "Sampling %s with frac=%.6f via runif filter to avoid extra H2O split frames.",
        reason,
        bounded_frac,
    )
    selector_key = f"selector_{re.sub(r'[^a-z0-9]+', '_', reason.lower())}_{seed}_{int(time.time() * 1000)}"
    selector = h2o.assign(frame.runif(seed=seed), selector_key)
    sampled = frame[selector <= bounded_frac]
    return sampled


def _safe_float(value, default=float("inf")) -> float:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return default
    if numeric != numeric:
        return default
    return numeric


def write_runtime_status(
    *,
    phase: str,
    message: str,
    status: str = "continue",
    models_logged: int | None = None,
) -> None:
    """Best-effort heartbeat updates for the Node3 status file during H2O work."""
    if not NODE3_STATUS_FILE:
        return

    try:
        status_path = Path(NODE3_STATUS_FILE)
        payload: dict = {}
        if status_path.exists():
            payload = json.loads(status_path.read_text(encoding="utf-8"))

        payload["status"] = status
        payload["phase"] = phase
        payload["message"] = message
        payload["updated_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        payload["pid"] = os.getpid()
        if RETRAIN_BATCH_ID:
            payload["batch_id"] = RETRAIN_BATCH_ID
        if models_logged is not None:
            payload["models_logged"] = int(models_logged)

        status_path.parent.mkdir(parents=True, exist_ok=True)
        status_path.write_text(
            json.dumps(payload, ensure_ascii=True, indent=2),
            encoding="utf-8",
        )
    except Exception as exc:
        logger.warning("Could not update runtime status file %s: %s", NODE3_STATUS_FILE, exc)


def collect_candidate_record(model, test_frame) -> dict:
    """Evaluate a model on the held-out test frame for consistent ranking."""
    performance = model.model_performance(test_frame)
    return {
        "model": model,
        "model_id": model.model_id,
        "algo": model.algo,
        "mean_per_class_error": _safe_float(
            getattr(performance, "mean_per_class_error", lambda: None)()
        ),
        "logloss": _safe_float(getattr(performance, "logloss", lambda: None)()),
        "rmse": _safe_float(getattr(performance, "rmse", lambda: None)()),
        "mse": _safe_float(getattr(performance, "mse", lambda: None)()),
    }


def candidate_sort_key(candidate: dict) -> tuple[float, float, str]:
    return (
        _safe_float(candidate.get("mean_per_class_error")),
        _safe_float(candidate.get("logloss")),
        str(candidate.get("model_id") or ""),
    )


def fallback_model_specs(seed: int) -> list[dict]:
    """Deterministic lightweight model plan used when AutoML under-fills the top-k."""
    return [
        {
            "algo": "gbm",
            "model_id": f"fallback_gbm_depth4_lr005_{seed}",
            "estimator": H2OGradientBoostingEstimator,
            "params": {
                "ntrees": 180,
                "max_depth": 4,
                "learn_rate": 0.05,
                "sample_rate": 0.8,
                "col_sample_rate": 0.8,
                "stopping_metric": "mean_per_class_error",
                "distribution": "multinomial",
                "max_runtime_secs": H2O_FALLBACK_PER_MODEL_RUNTIME_SECS,
                "seed": seed,
            },
        },
        {
            "algo": "gbm",
            "model_id": f"fallback_gbm_depth6_lr003_{seed}",
            "estimator": H2OGradientBoostingEstimator,
            "params": {
                "ntrees": 240,
                "max_depth": 6,
                "learn_rate": 0.03,
                "sample_rate": 0.75,
                "col_sample_rate": 0.75,
                "stopping_metric": "mean_per_class_error",
                "distribution": "multinomial",
                "max_runtime_secs": H2O_FALLBACK_PER_MODEL_RUNTIME_SECS,
                "seed": seed + 1,
            },
        },
        {
            "algo": "gbm",
            "model_id": f"fallback_gbm_depth8_lr002_{seed}",
            "estimator": H2OGradientBoostingEstimator,
            "params": {
                "ntrees": 320,
                "max_depth": 8,
                "learn_rate": 0.02,
                "sample_rate": 0.7,
                "col_sample_rate": 0.7,
                "stopping_metric": "mean_per_class_error",
                "distribution": "multinomial",
                "max_runtime_secs": H2O_FALLBACK_PER_MODEL_RUNTIME_SECS,
                "seed": seed + 2,
            },
        },
        {
            "algo": "gbm",
            "model_id": f"fallback_gbm_depth5_lr01_{seed}",
            "estimator": H2OGradientBoostingEstimator,
            "params": {
                "ntrees": 140,
                "max_depth": 5,
                "learn_rate": 0.1,
                "sample_rate": 0.8,
                "col_sample_rate": 0.8,
                "stopping_metric": "mean_per_class_error",
                "distribution": "multinomial",
                "max_runtime_secs": H2O_FALLBACK_PER_MODEL_RUNTIME_SECS,
                "seed": seed + 3,
            },
        },
        {
            "algo": "gbm",
            "model_id": f"fallback_gbm_depth3_lr015_{seed}",
            "estimator": H2OGradientBoostingEstimator,
            "params": {
                "ntrees": 120,
                "max_depth": 3,
                "learn_rate": 0.15,
                "sample_rate": 0.85,
                "col_sample_rate": 0.85,
                "stopping_metric": "mean_per_class_error",
                "distribution": "multinomial",
                "max_runtime_secs": H2O_FALLBACK_PER_MODEL_RUNTIME_SECS,
                "seed": seed + 4,
            },
        },
        {
            "algo": "gbm",
            "model_id": f"fallback_gbm_depth7_lr004_{seed}",
            "estimator": H2OGradientBoostingEstimator,
            "params": {
                "ntrees": 260,
                "max_depth": 7,
                "learn_rate": 0.04,
                "sample_rate": 0.75,
                "col_sample_rate": 0.75,
                "stopping_metric": "mean_per_class_error",
                "distribution": "multinomial",
                "max_runtime_secs": H2O_FALLBACK_PER_MODEL_RUNTIME_SECS,
                "seed": seed + 5,
            },
        },
        {
            "algo": "glm",
            "model_id": f"fallback_glm_alpha0025_{seed}",
            "estimator": H2OGeneralizedLinearEstimator,
            "params": {
                "family": "multinomial",
                "alpha": [0.025],
                "lambda_search": True,
                "standardize": True,
                "seed": seed + 6,
            },
        },
        {
            "algo": "glm",
            "model_id": f"fallback_glm_alpha0_{seed}",
            "estimator": H2OGeneralizedLinearEstimator,
            "params": {
                "family": "multinomial",
                "alpha": [0.0],
                "lambda_search": True,
                "standardize": True,
                "seed": seed + 7,
            },
        },
        {
            "algo": "glm",
            "model_id": f"fallback_glm_alpha05_{seed}",
            "estimator": H2OGeneralizedLinearEstimator,
            "params": {
                "family": "multinomial",
                "alpha": [0.5],
                "lambda_search": True,
                "standardize": True,
                "seed": seed + 8,
            },
        },
        {
            "algo": "glm",
            "model_id": f"fallback_glm_alpha1_{seed}",
            "estimator": H2OGeneralizedLinearEstimator,
            "params": {
                "family": "multinomial",
                "alpha": [1.0],
                "lambda_search": True,
                "standardize": True,
                "seed": seed + 9,
            },
        },
        {
            "algo": "naivebayes",
            "model_id": f"fallback_nb_laplace1_{seed}",
            "estimator": H2ONaiveBayesEstimator,
            "params": {
                "laplace": 1.0,
                "min_sdev": 0.001,
                "eps_sdev": 0.0,
            },
        },
        {
            "algo": "naivebayes",
            "model_id": f"fallback_nb_laplace05_{seed}",
            "estimator": H2ONaiveBayesEstimator,
            "params": {
                "laplace": 0.5,
                "min_sdev": 0.001,
                "eps_sdev": 0.0,
            },
        },
        {
            "algo": "naivebayes",
            "model_id": f"fallback_nb_laplace2_{seed}",
            "estimator": H2ONaiveBayesEstimator,
            "params": {
                "laplace": 2.0,
                "min_sdev": 0.001,
                "eps_sdev": 0.0,
            },
        },
    ]


def train_fallback_candidates(
    train,
    test,
    feature_columns: list[str],
    existing_model_ids: set[str],
    required_total: int,
) -> list[dict]:
    """Train additional deterministic candidates when AutoML does not fill the top-k."""
    candidates: list[dict] = []
    missing = max(0, required_total - len(existing_model_ids))
    if missing <= 0:
        return candidates

    logger.warning(
        "AutoML produced fewer than %s unique models; training fallback candidates to fill the leaderboard.",
        required_total,
    )
    for spec in fallback_model_specs(SEED):
        model_id = spec["model_id"]
        if model_id in existing_model_ids:
            continue

        estimator = spec["estimator"](model_id=model_id, **spec["params"])
        logger.info("Training fallback candidate %s (%s)...", model_id, spec["algo"])
        try:
            estimator.train(x=feature_columns, y=LABEL_COLUMN, training_frame=train)
            candidate = collect_candidate_record(estimator, test)
        except Exception as exc:
            logger.warning("Fallback candidate %s failed: %s", model_id, exc)
            continue

        logger.info(
            "Fallback candidate ready: %s mean_per_class_error=%.6f logloss=%.6f",
            candidate["model_id"],
            candidate["mean_per_class_error"],
            candidate["logloss"],
        )
        candidates.append(candidate)
        existing_model_ids.add(candidate["model_id"])
        if len(existing_model_ids) >= required_total:
            break

    return candidates


# ============================================================
# Find latest retrain data on GCS
# ============================================================
def find_latest_data(data_root: str) -> str | list[str]:
    """
    Find the most recent retrain data directory or file.

    Expected GCS structure:
        gs://bucket/features/retrain/20260510_14/
        gs://bucket/features/retrain/20260510_15/
        ...
    """
    if not data_root.startswith("gs://"):
        local_path = Path(data_root)
        if local_path.is_dir():
            candidate_files = sorted(
                [
                    path
                    for extension in ("*.csv", "*.parquet")
                    for path in local_path.rglob(extension)
                    if not _should_skip_local_training_file(path, local_path)
                ],
                key=lambda path: path.stat().st_mtime,
            )
            if candidate_files:
                logger.info(
                    "Using local retrain data directory: %s (%s supported files)",
                    data_root,
                    len(candidate_files),
                )
                return [str(path) for path in candidate_files]
            logger.warning(
                "Local retrain directory exists but contains no CSV or Parquet files: %s",
                data_root,
            )
        elif local_path.exists():
            logger.info("Using local retrain data path: %s", data_root)
            return data_root

        fallback = os.getenv(
            "US_TRAIN_OFFLINE_PATH",
            "data/process/us_train_offline_before_2020.csv",
        )
        logger.warning(
            "Local retrain path does not exist: %s. Falling back to %s",
            data_root,
            fallback,
        )
        return fallback

    try:
        # Use gsutil to list directories
        import subprocess

        result = subprocess.run(
            ["gsutil", "ls", "-d", f"{data_root}*/"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        dirs = [line.strip() for line in result.stdout.splitlines() if line.strip()]
        if not dirs:
            logger.warning(
                "No retrain directories found. Falling back to offline data."
            )
            return os.getenv(
                "OFFLINE_TRAIN_INPUT",
                "gs://big-data-group-4-bronze/process/us_train_offline_before_2020.csv",
            )

        # Sort and return the latest
        latest = sorted(dirs)[-1]
        logger.info("Latest retrain data directory: %s", latest)
        return latest
    except Exception as e:
        logger.warning(
            "Could not list GCS directories: %s. Using default data path.", e
        )
        return os.getenv(
            "OFFLINE_TRAIN_INPUT",
            "gs://big-data-group-4-bronze/process/us_train_offline_before_2020.csv",
        )


def _should_skip_local_training_file(path: Path, data_root: Path) -> bool:
    """Skip ad-hoc local test batches that should not enter cumulative retraining."""
    try:
        relative_parts = path.relative_to(data_root).parts
    except ValueError:
        relative_parts = path.parts

    if "incremental_batches" not in relative_parts:
        return False

    batch_index = relative_parts.index("incremental_batches") + 1
    if batch_index >= len(relative_parts):
        return False

    batch_id = relative_parts[batch_index]
    return not VALID_INCREMENTAL_BATCH_PATTERN.match(batch_id)


# ============================================================
# Main training function
# ============================================================
def main():
    # Find the latest merged retrain data
    data_path = find_latest_data(DEFAULT_DATA_PATH)

    logger.info("=" * 80)
    logger.info("H2O AutoML Retraining - Online / Incremental")
    logger.info("=" * 80)
    if isinstance(data_path, Sequence) and not isinstance(data_path, str):
        logger.info("Data files discovered:   %s", len(data_path))
        logger.info("Newest retrain file:     %s", data_path[-1] if data_path else "(none)")
        logger.info("Oldest retrain file:     %s", data_path[0] if data_path else "(none)")
    else:
        logger.info("Data path:               %s", data_path)
    logger.info("MLflow tracking URI:     %s", MLFLOW_TRACKING_URI)
    logger.info("MLflow experiment:       %s", MLFLOW_EXPERIMENT_NAME)
    logger.info("Registered model name:   %s", MODEL_NAME)
    logger.info("Max runtime (seconds):   %s", MAX_RUNTIME_SECS)
    logger.info("Max models:              %s", H2O_MAX_MODELS)
    logger.info("Top models to log:       %s", TOP_K_MODELS)
    logger.info("H2O max memory:          %s", H2O_MAX_MEM)
    logger.info("H2O threads:             %s", H2O_NTHREADS)
    logger.info("Random seed:             %s", SEED)
    logger.info("Retrain batch ID:        %s", RETRAIN_BATCH_ID or "(not provided)")
    logger.info("H2O nfolds:              %s", H2O_NFOLDS)
    logger.info("H2O exclude algos:       %s", H2O_EXCLUDE_ALGOS or "[]")
    logger.info("H2O balance classes:     %s", H2O_BALANCE_CLASSES)
    if H2O_TRAIN_MAX_ROWS > 0:
        logger.info("H2O train max rows:      %s", f"{H2O_TRAIN_MAX_ROWS:,}")
    else:
        logger.info("H2O train max rows:      disabled")
    logger.info("H2O max after balance:   %s", H2O_MAX_AFTER_BALANCE_SIZE)
    logger.info("H2O max secs / model:    %s", H2O_MAX_RUNTIME_SECS_PER_MODEL)
    logger.info("Fallback secs / model:   %s", H2O_FALLBACK_PER_MODEL_RUNTIME_SECS)

    # ---- Step 1: Initialize H2O cluster ----
    logger.info("Step 1: Initializing H2O cluster...")
    shutdown_existing_local_h2o()
    h2o.init(
        ip=H2O_IP,
        port=H2O_PORT,
        max_mem_size=H2O_MAX_MEM,
        nthreads=H2O_NTHREADS,
    )
    logger.info("H2O cluster initialized.")

    # ---- Step 2: Configure MLflow ----
    logger.info("Step 2: Configuring MLflow tracking...")
    mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
    mlflow.set_experiment(MLFLOW_EXPERIMENT_NAME)

    # ---- Step 3: Load data ----
    logger.info("Step 3: Loading retrain data from: %s", data_path)
    df_h2o = h2o.import_file(data_path)
    logger.info("Loaded %s rows, %s columns", f"{df_h2o.nrows:,}", df_h2o.ncols)

    df_h2o[LABEL_COLUMN] = df_h2o[LABEL_COLUMN].asfactor()

    label_dist = df_h2o[LABEL_COLUMN].table()
    logger.info("Label distribution:\n%s", label_dist)
    class_sampling_factors, class_sampling_metadata = build_class_sampling_factors(
        label_dist
    )
    if class_sampling_factors:
        logger.info(
            "Class sampling labels:  %s",
            class_sampling_metadata["ordered_labels"],
        )
        logger.info("Class sampling factors: %s", class_sampling_factors)

    # ---- Step 4: Train/test split ----
    logger.info("Step 4: Splitting into train/test (80/20)...")
    feature_columns = [c for c in df_h2o.columns if c not in EXCLUDED_COLUMNS]
    logger.info("Feature columns (%s): %s", len(feature_columns), feature_columns)
    logger.info("Label column:         %s", LABEL_COLUMN)

    sampled_source = df_h2o
    if H2O_TRAIN_MAX_ROWS > 0:
        target_total_rows = int(H2O_TRAIN_MAX_ROWS / 0.8)
        if sampled_source.nrows > target_total_rows:
            frac = target_total_rows / float(sampled_source.nrows)
            logger.warning(
                "Sampling source frame from %s rows to ~%s rows before train/test split (frac=%.6f) for stability.",
                f"{sampled_source.nrows:,}",
                f"{target_total_rows:,}",
                frac,
            )
            sampled_source = sample_frame_rows(
                sampled_source,
                frac=frac,
                seed=SEED,
                reason="source retrain frame",
            )
            logger.info(
                "Sampled source rows: %s",
                f"{sampled_source.nrows:,}",
            )

    split_selector = h2o.assign(
        sampled_source.runif(seed=SEED),
        f"selector_train_test_{SEED}_{int(time.time() * 1000)}",
    )
    train = sampled_source[split_selector <= 0.8]
    test = sampled_source[split_selector > 0.8]

    if H2O_TRAIN_MAX_ROWS > 0 and train.nrows > H2O_TRAIN_MAX_ROWS:
        frac = H2O_TRAIN_MAX_ROWS / float(train.nrows)
        logger.warning(
            "Downsampling train frame from %s rows to ~%s rows (frac=%.6f) for stability.",
            f"{train.nrows:,}",
            f"{H2O_TRAIN_MAX_ROWS:,}",
            frac,
        )
        train = sample_frame_rows(
            train,
            frac=frac,
            seed=SEED,
            reason="training frame",
        )
    logger.info("Training rows:   %s", f"{train.nrows:,}")
    logger.info("Test rows:       %s", f"{test.nrows:,}")
    if sampled_source is not df_h2o:
        try:
            h2o.remove(df_h2o.frame_id)
        except Exception:
            pass

    # ---- Step 6: Train H2O AutoML ----
    logger.info("Step 6: Starting H2O AutoML retraining...")
    logger.info("Max runtime: %s seconds", MAX_RUNTIME_SECS)
    write_runtime_status(
        phase="h2o",
        message="H2O AutoML retraining started.",
        models_logged=0,
    )

    with mlflow.start_run(run_name="h2o_retrain_online") as run:
        run_id = run.info.run_id
        logger.info("MLflow run ID: %s", run_id)

        mlflow.set_tag("run_type", "retrain_online")
        mlflow.set_tag("run_role", "retrain_parent")
        if RETRAIN_BATCH_ID:
            mlflow.set_tag("retrain_batch_id", RETRAIN_BATCH_ID)
        mlflow.log_param("run_type", "retrain_online")
        mlflow.log_param("top_k_models", TOP_K_MODELS)
        mlflow.log_param("max_models", H2O_MAX_MODELS)
        mlflow.log_param("enforce_full_top_k", H2O_ENFORCE_FULL_TOP_K)
        mlflow.log_param("max_runtime_secs", MAX_RUNTIME_SECS)
        mlflow.log_param("seed", SEED)
        mlflow.log_param("nfolds", H2O_NFOLDS)
        mlflow.log_param("exclude_algos", ",".join(H2O_EXCLUDE_ALGOS))
        mlflow.log_param("balance_classes", H2O_BALANCE_CLASSES)
        mlflow.log_param("train_max_rows", H2O_TRAIN_MAX_ROWS)
        mlflow.log_param("eval_max_rows", H2O_EVAL_MAX_ROWS)
        mlflow.log_param("max_after_balance_size", H2O_MAX_AFTER_BALANCE_SIZE)
        mlflow.log_param("max_runtime_secs_per_model", H2O_MAX_RUNTIME_SECS_PER_MODEL)
        mlflow.log_param("n_features", len(feature_columns))
        mlflow.log_param("n_train_rows", train.nrows)
        mlflow.log_param("n_test_rows", test.nrows)
        mlflow.log_param("data_path", data_path)
        if RETRAIN_BATCH_ID:
            mlflow.log_param("retrain_batch_id", RETRAIN_BATCH_ID)
        if class_sampling_factors:
            mlflow.log_param(
                "class_sampling_labels",
                ",".join(class_sampling_metadata["ordered_labels"]),
            )
            mlflow.log_param(
                "class_sampling_factors",
                ",".join(str(value) for value in class_sampling_factors),
            )
            mlflow.log_param(
                "max_class_sampling_factor",
                class_sampling_metadata["max_class_sampling_factor"],
            )

        automl_parameters = {
            "max_runtime_secs": MAX_RUNTIME_SECS,
            "max_runtime_secs_per_model": H2O_MAX_RUNTIME_SECS_PER_MODEL,
            "max_models": H2O_MAX_MODELS,
            "seed": SEED,
            "project_name": "traffic_risk_retrain",
            "balance_classes": H2O_BALANCE_CLASSES,
            "max_after_balance_size": H2O_MAX_AFTER_BALANCE_SIZE,
            "sort_metric": "mean_per_class_error",
            "nfolds": H2O_NFOLDS,
        }
        if H2O_EXCLUDE_ALGOS:
            automl_parameters["exclude_algos"] = H2O_EXCLUDE_ALGOS
        if H2O_BALANCE_CLASSES and class_sampling_factors:
            automl_parameters["class_sampling_factors"] = class_sampling_factors

        aml = H2OAutoML(**automl_parameters)

        aml.train(
            x=feature_columns,
            y=LABEL_COLUMN,
            training_frame=train,
        )

        logger.info("Training completed.")
        write_runtime_status(
            phase="h2o",
            message="AutoML search completed. Ranking candidate models.",
            models_logged=0,
        )

        # ---- Step 7: Leaderboard ----
        lb = aml.leaderboard
        lb_df = lb.as_data_frame()
        logger.info("H2O AutoML leaderboard:\n%s", lb_df.head(TOP_K_MODELS))

        # ---- Step 8: Evaluate and log top 10 models ----
        automl_model_ids = lb_df["model_id"].tolist()
        if not automl_model_ids:
            raise RuntimeError("H2O AutoML produced no leaderboard models.")
        candidate_records = []
        seen_model_ids: set[str] = set()
        for model_id in automl_model_ids:
            if model_id in seen_model_ids:
                continue
            candidate_records.append(
                collect_candidate_record(h2o.get_model(model_id), test)
            )
            seen_model_ids.add(model_id)

        if len(candidate_records) < TOP_K_MODELS:
            message = (
                f"AutoML returned only {len(candidate_records)} unique models, fewer than "
                f"the required top-{TOP_K_MODELS}. Training fallback candidates."
            )
            logger.warning(message)
            mlflow.set_tag("fallback_top_k_fill", "true")
            candidate_records.extend(
                train_fallback_candidates(
                    train,
                    test,
                    feature_columns,
                    seen_model_ids,
                    TOP_K_MODELS,
                )
            )

        candidate_records.sort(key=candidate_sort_key)
        ranking_df = pd.DataFrame(
            [
                {
                    "model_id": candidate["model_id"],
                    "algo": candidate["algo"],
                    "mean_per_class_error": candidate["mean_per_class_error"],
                    "logloss": candidate["logloss"],
                    "rmse": candidate["rmse"],
                    "mse": candidate["mse"],
                }
                for candidate in candidate_records
            ]
        )
        logger.info(
            "Combined candidate leaderboard (top %s):\n%s",
            TOP_K_MODELS,
            ranking_df.head(TOP_K_MODELS),
        )

        top_candidates = candidate_records[:TOP_K_MODELS]
        top_model_ids = [candidate["model_id"] for candidate in top_candidates]
        write_runtime_status(
            phase="logging_models",
            message=f"Evaluating and logging top {len(top_model_ids)} models.",
            models_logged=0,
        )
        if len(top_model_ids) < TOP_K_MODELS:
            message = (
                f"Only {len(top_model_ids)} models were available after fallback training, "
                f"still below the required top-{TOP_K_MODELS}."
            )
            if H2O_ENFORCE_FULL_TOP_K:
                raise RuntimeError(message)
            logger.warning(message)
        logger.info(
            "Step 8: Evaluating and logging top %s models...", len(top_model_ids)
        )

        best_model = None
        best_rank = None
        best_macro_f1 = -1.0
        best_logloss = float("inf")
        best_metrics = {}

        for rank, candidate in enumerate(top_candidates, start=1):
            model_id = candidate["model_id"]
            model = candidate["model"]
            model_perf = model.model_performance(test)
            sklearn_metrics, report_df, confusion_df = evaluate_classifier_with_sklearn(
                model,
                test,
                feature_columns,
                LABEL_COLUMN,
            )

            current_logloss = float(model_perf.logloss())
            current_macro_f1 = sklearn_metrics["macro_f1"]
            if current_macro_f1 > best_macro_f1 or (
                current_macro_f1 == best_macro_f1 and current_logloss < best_logloss
            ):
                best_macro_f1 = current_macro_f1
                best_logloss = current_logloss
                best_model = model
                best_rank = rank
                best_metrics = sklearn_metrics

            logger.info("-" * 60)
            logger.info("Evaluating model rank %d: %s (%s)", rank, model_id, model.algo)

            with mlflow.start_run(
                run_name=f"retrain_top{rank}_{model.algo}", nested=True
            ):
                mlflow.set_tag("run_type", "retrain_online")
                mlflow.set_tag("run_role", "leaderboard_model")
                if RETRAIN_BATCH_ID:
                    mlflow.set_tag("retrain_batch_id", RETRAIN_BATCH_ID)
                mlflow.log_param("rank", rank)
                mlflow.log_param("model_id", model_id)
                mlflow.log_param("algo", model.algo)
                mlflow.log_param(
                    "leaderboard_source",
                    "automl" if model_id in automl_model_ids else "fallback",
                )
                if RETRAIN_BATCH_ID:
                    mlflow.log_param("retrain_batch_id", RETRAIN_BATCH_ID)

                log_metric_if_exists(model_perf, "logloss")
                log_metric_if_exists(model_perf, "mean_per_class_error")
                log_metric_if_exists(model_perf, "accuracy")
                log_metric_if_exists(model_perf, "rmse")
                log_metric_if_exists(model_perf, "mse")
                log_metric_if_exists(model_perf, "r2")
                log_metric_if_exists(model_perf, "auc")
                log_metric_if_exists(model_perf, "gini")
                log_metric_if_exists(model_perf, "F1")
                log_metric_if_exists(model_perf, "precision")
                log_metric_if_exists(model_perf, "recall")
                log_classifier_metrics(
                    sklearn_metrics,
                    report_df,
                    confusion_df,
                    artifact_prefix=f"retrain_rank{rank}_{model.algo}",
                )

                try:
                    if hasattr(model_perf, "confusion_matrix"):
                        cm = model_perf.confusion_matrix()
                        logger.info("  Confusion matrix:\n%s", cm)
                except (KeyError, AttributeError):
                    pass

                mlflow.h2o.log_model(model, artifact_path=f"retrain_model_rank{rank}")
                write_runtime_status(
                    phase="logging_models",
                    message=f"Logged retrain top {rank}/{len(top_candidates)}: {model_id}",
                    models_logged=rank,
                )

        # ---- Step 9: Register best model ----
        if best_model is None or not best_metrics:
            raise RuntimeError("No retrained model passed evaluation.")

        logger.info("=" * 60)
        logger.info("Registering the best retrained model...")
        logger.info("Best model ID: %s", best_model.model_id)
        logger.info("Best model algorithm: %s", best_model.algo)
        logger.info("Best model macro F1: %.6f", best_macro_f1)
        logger.info(
            "Best model weighted F1: %.6f", best_metrics.get("weighted_f1", 0.0)
        )
        logger.info("Best model logloss: %.6f", best_logloss)

        mlflow.log_param("best_model_rank", best_rank)
        mlflow.log_param("best_model_id", best_model.model_id)
        mlflow.log_param("best_model_algo", best_model.algo)
        mlflow.log_param("candidate_models_available", len(candidate_records))
        mlflow.log_metric("models_logged", len(top_model_ids))
        mlflow.log_metric("logloss", best_logloss)
        for metric_name, metric_value in best_metrics.items():
            mlflow.log_metric(metric_name, metric_value)

        mlflow.h2o.log_model(best_model, artifact_path="best_model")
        write_runtime_status(
            phase="registering_model",
            message=f"Registering best model {best_model.model_id}.",
            models_logged=len(top_model_ids),
        )

        model_uri = f"runs:/{run_id}/best_model"
        registered_model = mlflow.register_model(model_uri, MODEL_NAME)
        logger.info(
            "Model registered: name=%s, version=%s",
            registered_model.name,
            registered_model.version,
        )

        logger.info("Flink will automatically load models:/%s/latest", MODEL_NAME)
        write_runtime_status(
            phase="completed",
            message="H2O retraining finished successfully.",
            models_logged=len(top_model_ids),
        )

    # ---- Cleanup ----
    logger.info("Shutting down H2O cluster...")
    h2o.shutdown(prompt=False)

    logger.info("=" * 80)
    logger.info("Retraining complete. New model version in MLflow Registry.")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
